/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delhidarshan;

/**
 *
 * @author user
 */
public class Greeter extends javax.swing.JFrame {

    /**
     * Creates new form Greeter
     */
    public Greeter() {
        initComponents();
        infotrans.setLineWrap(true);
        infoacco.setLineWrap(true);
        infoeat.setLineWrap(true);
        infoent.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rail = new javax.swing.JButton();
        road = new javax.swing.JButton();
        air = new javax.swing.JButton();
        metro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infotrans = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        hotels = new javax.swing.JButton();
        motels = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoacco = new javax.swing.JTextArea();
        luxuryhotels = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cuisine = new javax.swing.JButton();
        restrau = new javax.swing.JButton();
        dhaba = new javax.swing.JButton();
        fast = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoeat = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        monuments = new javax.swing.JButton();
        museum = new javax.swing.JButton();
        theater = new javax.swing.JButton();
        gallery = new javax.swing.JButton();
        worship = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoent = new javax.swing.JTextArea();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to Delhi !!");

        rail.setText("Rail");
        rail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                railActionPerformed(evt);
            }
        });

        road.setText("Road");
        road.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roadActionPerformed(evt);
            }
        });

        air.setText("Air");
        air.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airActionPerformed(evt);
            }
        });

        metro.setText("Metro");
        metro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metroActionPerformed(evt);
            }
        });

        infotrans.setColumns(20);
        infotrans.setRows(5);
        jScrollPane1.setViewportView(infotrans);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(metro)
                    .addComponent(air)
                    .addComponent(road)
                    .addComponent(rail))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rail)
                        .addGap(18, 18, 18)
                        .addComponent(road)
                        .addGap(20, 20, 20)
                        .addComponent(air)
                        .addGap(18, 18, 18)
                        .addComponent(metro)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transport", jPanel1);

        hotels.setText("Hotels");
        hotels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelsActionPerformed(evt);
            }
        });

        motels.setText("Motels");
        motels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motelsActionPerformed(evt);
            }
        });

        infoacco.setColumns(20);
        infoacco.setRows(5);
        jScrollPane2.setViewportView(infoacco);

        luxuryhotels.setText("Luxury Hotels");
        luxuryhotels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luxuryhotelsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(luxuryhotels)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(motels)
                            .addComponent(hotels))
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(hotels)
                        .addGap(28, 28, 28)
                        .addComponent(motels)
                        .addGap(29, 29, 29)
                        .addComponent(luxuryhotels)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Accomodation", jPanel2);

        cuisine.setText("Cuisines");
        cuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineActionPerformed(evt);
            }
        });

        restrau.setText("Restaurant");
        restrau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restrauActionPerformed(evt);
            }
        });

        dhaba.setText("Dhaba");
        dhaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhabaActionPerformed(evt);
            }
        });

        fast.setText("Fast Food");
        fast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastActionPerformed(evt);
            }
        });

        infoeat.setColumns(20);
        infoeat.setRows(5);
        jScrollPane3.setViewportView(infoeat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fast)
                    .addComponent(dhaba)
                    .addComponent(restrau)
                    .addComponent(cuisine))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cuisine)
                        .addGap(29, 29, 29)
                        .addComponent(restrau)
                        .addGap(30, 30, 30)
                        .addComponent(dhaba)
                        .addGap(29, 29, 29)
                        .addComponent(fast)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eateries", jPanel3);

        monuments.setText("Monuments");
        monuments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monumentsActionPerformed(evt);
            }
        });

        museum.setText("Parks, Museum");
        museum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                museumActionPerformed(evt);
            }
        });

        theater.setText("Theater");
        theater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theaterActionPerformed(evt);
            }
        });

        gallery.setText("Art Galleries");
        gallery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleryActionPerformed(evt);
            }
        });

        worship.setText("Places of Worship");
        worship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worshipActionPerformed(evt);
            }
        });

        infoent.setColumns(20);
        infoent.setRows(5);
        jScrollPane4.setViewportView(infoent);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(worship)
                    .addComponent(gallery)
                    .addComponent(theater)
                    .addComponent(museum)
                    .addComponent(monuments))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(monuments)
                        .addGap(18, 18, 18)
                        .addComponent(museum)
                        .addGap(20, 20, 20)
                        .addComponent(theater)
                        .addGap(27, 27, 27)
                        .addComponent(gallery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(worship)
                        .addGap(20, 20, 20))))
        );

        jTabbedPane1.addTab("Entertainment", jPanel4);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(224, 224, 224))))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(exit)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void railActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_railActionPerformed
        // TODO add your handling code here:
        infotrans.setText("New Delhi is a major junction in the Indian railway network and is the headquarters of the Northern Railway. The five main railway stations are New Delhi railway station, Old Delhi, Nizamuddin Railway Station, Anand Vihar Railway Terminal and Sarai Rohilla.[55] The Delhi Metro, a mass rapid transit system built and operated by Delhi Metro Rail Corporation (DMRC), serves many parts of Delhi and the neighbouring cities Gurgaon, Noida and Ghaziabad. As of August 2011, the metro consists of six operational lines with a total length of 189 km (117 mi) and 146 stations, and several other lines are under construction.[56] It carries millions of passengers every day.[57] In addition to the Delhi Metro, a suburban railway, the Delhi Suburban Railway exists");
    }//GEN-LAST:event_railActionPerformed

    private void roadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roadActionPerformed
        // TODO add your handling code here:
        infotrans.setText("New Delhi has one of India's largest bus transport systems. Buses are operated by the state-owned Delhi Transport Corporation (DTC), which owns largest fleet of Compressed Natural Gas (CNG)-fueled buses in the world. Personal vehicles especially cars also form a major chunk of vehicles plying on New Delhi roads. New Delhi has the highest number of registered cars compared to any other metropolitan city in India. Taxis and Auto Rickshaws also ply on New Delhi roads in large numbers. New Delhi has one of the highest road density in India. Important Roads in New Delhi\n" +
"\n" +
"Some roads and expressways serve as important pillars of New Delhi's road infrastructure:\n" +
"\n" +
"    Inner Ring Road is one of the most important \"state highways\" in New Delhi. It is a 51 km long circular road, which connects important areas in New Delhi. Owing to more than 2 dozen grade-separators/flyovers, the road is almost signal-free.\n" +
"    Outer Ring Road is another major artery in New Delhi that links far-flung areas of Delhi.\n" +
"    The Delhi Noida Direct Flyway (DND Flyway) is an eight-laned access controlled tolled expressway which connects New Delhi and Delhi to Noida (an important satellite city of Uttar Pradesh). The acronym DND stands for \"Delhi-Noida Direct\".\n" +
"    'The Delhi Gurgaon Expressway is a 28 km (17 mi) expressway connecting New Delhi to Gurgaon, an important satellite city of Haryana.\n" +
"    The Delhi Faridabad Skyway is controlled tolled expressway which connects New Delhi to Faridabad, an important satellite city of Haryana.\n" +
"\n" +
"National Highways Passing Through New Delhi\n" +
"\n" +
"New Delhi is connected by Road to various parts of the country through several National highways:\n" +
"\n" +
"    National Highway 1 (India) or (NH 1) is a National Highway in Northern India that links the National capital New Delhi to the town of Attari in Punjab, India near the Indo-Pakistani border. NH ! follows a section of the historic two millennia old Grand Trunk Road that runs from Afghanistan, through Pakistan and India, to Bangladesh.\n" +
"    National Highway 2 (India) (NH 2), commonly referred as Delhi-Kolkata Road is a busy Indian National Highway that runs through the states of Delhi, Haryana, Uttar Pradesh, Bihar, Jharkhand, and West Bengal.\n" +
"    National Highway 8 (India) (NH 8), is a National Highway in India that connects the Indian capital city of New Delhi with the Indian Financial capital city of Mumbai.\n" +
"    National Highway 10 (India) (NH 10) is a National Highway in northern India that originates at Delhi and ends at the town of Fazilka in Punjab, India near the Indo-Pakistani border.\n" +
"    National Highway 24 (India) (NH 24) is a National Highway in India that connects the National capital New Delhi to Uttar Pradesh state capital Lucknow running 438 kilometers in length.");
    }//GEN-LAST:event_roadActionPerformed

    private void airActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airActionPerformed
        // TODO add your handling code here:
        infotrans.setText("Indira Gandhi International Airport, situated to the southwest of Delhi, is the main gateway for the city's domestic and international civilian air traffic. In 2012-13, the airport was used by more than 35 million passengers,[46][47] making it one of the busiest airports in South Asia. Terminal 3, which cost ₹96.8 billion (US$1.5 billion) to construct between 2007 and 2010, handles an additional 37 million passengers annually.[48]\n" +
"\n" +
"The Delhi Flying Club, established in 1928 with two de Havilland Moth aircraft named Delhi and Roshanara, was based at Safdarjung Airport which started operations in 1929, when it was the Delhi's only airport and the second in India.[49] The airport functioned until 2001, however in January 2002 the government closed the airport for flying activities because of security concerns following the New York attacks in September 2001. Since then, the club only carries out aircraft maintenance courses,[49] and is used for helicopter rides to Indira Gandhi International Airport for VIP including the president and the prime minister.[50]\n" +
"\n" +
"In 2010, Indira Gandhi International Airport (IGIA) was conferred the fourth best airport award in the world in the 15–25 million category, and Best Improved Airport in the Asia-Pacific Region by Airports Council International.[51] The airport was rated as the Best airport in the world in the 25–40 million passengers category in 2015, by Airports Council International.[52][53] Delhi Airport also bags two awards for The Best Airport in Central Asia/India and Best Airport Staff in Central Asia/India at the Skytrax World Airport Awards 2015");
    }//GEN-LAST:event_airActionPerformed

    private void metroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metroActionPerformed
        // TODO add your handling code here:
        infotrans.setText("The Delhi Metro is a rapid transit system serving New Delhi, Delhi, Gurgaon, Faridabad, Noida, and Ghaziabad in the National Capital Region of India. Delhi Metro is the world's 13th largest metro system in terms of length. Delhi Metro was India's first modern public transportation system, which had revolutionised travel by providing a fast, reliable, safe, and comfortable means of transport. The network consists of six lines with a total length of 189.63 kilometres (117.83 miles) with 142 stations, of which 35 are underground, five are at-grade, and the remainder are elevated. All stations have escalators, elevators, and tactile tiles to guide the visually impaired from station entrances to trains. It has a combination of elevated, at-grade, and underground lines, and uses both broad gauge and standard gauge rolling stock. Four types of rolling stock are used: Mitsubishi-ROTEM Broad gauge, Bombardier MOVIA, Mitsubishi-ROTEM Standard gauge, and CAF Beasain Standard gauge.\n" +
"\n" +
"Delhi Metro is being built and operated by the Delhi Metro Rail Corporation Limited (DMRC), a state-owned company with equal equity participation from Government of India and Government of National Capital Territory of Delhi. However, the organisation is under administrative control of Ministry of Urban Development, Government of India. Besides construction and operation of Delhi metro, DMRC is also involved in the planning and implementation of metro rail, monorail and high-speed rail projects in India and providing consultancy services to other metro projects in the country as well as abroad. The Delhi Metro project was spearheaded by Padma Vibhushan E. Sreedharan, the Managing Director of DMRC and popularly known as the \"Metro Man\" of India. He famously resigned from DMRC, taking moral responsibility for a metro bridge collapse which took five lives. Sreedharan was awarded with the prestigious Legion of Honour by the French Government for his contribution to Delhi Metro.");
    }//GEN-LAST:event_metroActionPerformed

    private void hotelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelsActionPerformed
        // TODO add your handling code here:
        infoacco.setText("    Airlines, Arakshan Road, Paharganj Phone: 23617571\n" +
"    Ajanta, 36 Arakshan Roa, Ram Nagar Phone: 29562097,41764563\n" +
"    Ashoka Guest House, Katra Lachoo Singh, Chandni Chowk Phone: 23865007\n" +
"    Chanakya, Rajguru Road, Paharganj Phone: 23588823/28\n" +
"    Citizen, 5285 Ajmeri Gate Phone: 23670076\n" +
"    Crown, 0208 Katra Bariyan, Fatehpuri Phone: 23957599\n" +
"    Imperial, Fatehpuri, Delhi - 110006, Phone:23947510/6053\n" +
"    Kabeer, ¾ Arakshan Road, Ram Nagar Phone: 23621300\n" +
"    Kapoor Holiday Inn, F-39 East Of Kailash Phone: 26415600, 26432457, 26432228\n" +
"    Natraj, 1750 Chuna Mandi, Paharganj Phone: 23580099\n" +
"    South India, 1211 Padam Singh Road, Karol Bagh Phone: 28756025/3651\n" +
"    Tourist, 7361 Ram Nagar, Near Qutab Road Pahar Ganj. Phone: 23610334\n" +
"    Tourist Home, 2501 Arakshan Road, Paharganj Phone: 23673473\n" +
"    Tourist Inn, 8502 Arakshan Road, Paharganj Phone: 23677112\n" +
"    Wood Inn, 8 Furniture Block, Kirti Nagar Phone: 25438500, 25439136");
    }//GEN-LAST:event_hotelsActionPerformed

    private void motelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motelsActionPerformed
        // TODO add your handling code here:
        infoacco.setText("    Ambassador, Sujan Singh Park Phone: 24632600\n" +
"    Ashok, 50B Chanakyapuri Phone: 26110101\n" +
"    Ashok Country Resort, Rajokari Road, Kapashera Phone: 25064590/99, 25063295\n" +
"    Centaur, Indira Gandhi International Airport Phone: 25652223\n" +
"    Crowne Plaza Surya, New Friends Colony Phone: 26835070\n" +
"    Diplomat, 9 Sardar Patel Marg Phone: 23010204\n" +
"    Hyatt Regency - R.K.Puram New Delhi Phone: 26791234\n" +
"    Le Meridian , 1 Windsor Place Janpath Phone: 23710101\n" +
"    Grand Inter-Continental, Barakhamba Avenue Phone: 23411001\n" +
"    Imperial, Janpath Phone:23341234, 23345678\n" +
"    Hyatt Regency Delhi, Bhikaji Cama Place Phone: 26791234\n" +
"    Hans Plaza, 15 Barakhamba Road Phone: 23316868\n" +
"    Grand Hyatt, Nelson Mandela Road, Vasant Kunj Phase II Phone: 26771234\n" +
"    Marriott Welcome Hotel, District Centre, Saket Phone: 42661122\n" +
"    Maurya Sheraton & Towers, Sardar Patel Marg, Diplomatic Enclave Phone: 26112233\n" +
"    Metropolitan-Hotel Nikko, Bangla Sahib Road Phone: 42300200\n" +
"    Oberoi Maidens, 7 Sham Nath Marg Phone: 23975464\n" +
"    Park Royal Inter-Continental , Nehru Place Phone: 26223344\n" +
"    Qutab, Shaheed Jeet Singh Marg Phone:26521010/1234\n" +
"    Radisson Delhi, Sikanderpur, N.H. 8 Phone: 26779191\n" +
"    Samrat, 20B Kautilya Marg, Chanakyapuri Phone: 26110606\n" +
"    Siddharth, 3 Rajendra Place Phone: 25762501\n" +
"    Taj Mahal, 1 Mansingh Road Phone: 23026162\n" +
"    Taj Palace, 2 Sardar Patel Marg Phone: 26110202\n" +
"    The Claridges, 12 Aurangzeb Road Phone: 39555000\n" +
"    The Oberoi, Dr. Zakir Hussain Marg Phone: 24363030\n" +
"    The Park, 15 Parliament Street Phone: 23743737\n" +
"    The Tivoli Garden Resort, Chhattarpur Mandir Road Phone: 26301111\n" +
"    Uppal's Orchid, N.H. 8, Near I.G.I. Airport Phone: 25061515\n" +
"    Vasant Continental, Vasant Vihar Phone: 26148800\n" +
"");
    }//GEN-LAST:event_motelsActionPerformed

    private void luxuryhotelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luxuryhotelsActionPerformed
        // TODO add your handling code here:
        infoacco.setText("Arien International, E189 Kalkaji Phone: 26294040/41\n" +
"Bright Star, B3 Greater Kailash Enclave-I Phone: 46566660\n" +
"Broadway, 4/15A Asaf Ali Road Phone: 23273831\n" +
"Central Court, N Block, Connaught Circus.\n" +
"City Park, KP Block, Pitampura Phone: 27310101\n" +
"Clark Inn, 4/27 WEA, Saraswati Marg Karol Bagh Phone: 25760225\n" +
"Classic, 17A/59 WEA, Karol Bagh Phone: 25746060/7070\n" +
"Corporate World Inn, B-495 New Friends Colony Phone: 41627165\n" +
"Host Inn, F33 Connaught Place Phone: 23310431/523\n" +
"Indraprasth, H 58 Vikas Marg, Laxmi Nagar Phone: 22007375\n" +
"International Inn, 9A Ring Road, Lajpat Nagar-IV Phone: 26437391\n" +
"Janpath Guest House, 82-84 Janpath Phone: 23321935/6\n" +
"Jor Bagh, 27 Jor Bagh Phone: 24698475\n" +
"Jukaso Inn, 49/50 Sunder Nagar Phone: 24350308/09\n" +
"Kailash International, E364 Nirman Vihar Phone: 22521887\n" +
"Kumar Holiday Home, 33 Ring Road, Lajpat Nagar-IV Phone: 26411874\n" +
"La Sagrita Tourist Home, 14 Sunder Nagar Phone: 24601249\n" +
"Lisa Inn, F46 South Extension-I Phone: 24623576\n" +
"Lodhi, Lala Lajpat Rai Marg Phone: 24362422\n" +
"Madhuban Holiday Inn, B11 Greater Kailash-I Phone: 26431923\n" +
"Maharani Guest House, 3 Sunder Nagar Phone: 24359521 - 23\n" +
"Manor, 77 Friends Colony(Weat) Phone:26925151/7510\n" +
"Marina, G59 Connaught Circus Phone: 23324658\n" +
"Metro, N49 Connaught Circus Phone: 23313805/56, 23315481\n" +
"M.D. International Inn, C2/12 Safdarjang Development Area Phone: 26966625, 26865546\n" +
"Metropolis Tourist Home, 1634 Main Bazar, Paharganj Phone: 23558052\n" +
"Neeru, 10 Netaji Subhash Marg, Darya Ganj Phone: 23278522/756\n" +
"Nirula's, L-Block, Connaught Circus Phone: 23417419, 51517071/77\n" +
"Orchid, G4 South Extension-I Phone: 24643529\n" +
"Panchsheel Guest House, C4 Panchsheel Enclave Phone: 26444158\n" +
"Park Residency, D1 Green Park Phone: 26533684/85/86\n" +
"Park View, 15A/60 WEA, Karol Bagh Phone: 25750303/04\n" +
"Rajdoot, 14 Mathura Road Phone: 24316666, 24376404\n" +
"Rockland, C30 Panchsheel Enclave Phone: 26499780-83\n" +
"Rockland Inn, B207 Chitranjan Park Phone: 26445854\n" +
"Rosewood Inn, C55 South Extension-II Phone: 26262794, 26263922/23\n" +
"Sartaj, A3 Green Park Phone: 2685760/02/04/06\n" +
"Satkar, Aurbindo Marg, Green Park Phone: 26567811\n" +
"Shanti Palace, A67 Mahipalpur Extn. Phone: 26781271-76\n" +
"Shervani Fortview, 11 Sunder Nagar Phone: 24359670/4771/5831\n" +
"Shiela, Pahwa House, 9 Qutab Road Phone: 23525603\n" +
"Silver Oak, B46 Soami Nagar Phone: 26016367\n" +
"Sobti, 2397 Hardhian Singh Road, Karol Bagh Phone: 25729035/7");
    }//GEN-LAST:event_luxuryhotelsActionPerformed

    private void cuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuisineActionPerformed
        // TODO add your handling code here:
        infoeat.setText("From age-old eateries in the by lanes of the Walled City to glitzy, specialty restaurants in five-star hotels, Delhi is a foodie's paradise. Delhi offers a choice of Indian and International Cuisines in different ambiences to suit varied budgets.\n" +
"\n" +
"For gourmets, Delhi is synonymous with Mughlai and Frontier Cuisine. The best of Mughlai cuisine can be enjoyed at Karim, (both in Jama Masjid and Nizamuddin) where the recipes, dating from the times of the Mughals have been the closely guarded secrets of generations of chefs.\n" +
"\n" +
"Delhi ka Aangan (Hyatt Regency), Darbar (Ashoka Hotel), and Corbetts (Claridges) are among the many options available in the expensive range, while Gulati Restaurant (Pandara Market), Angeethi (Asiad Village) and Degchi (Regal Building) are among those catering to more modest budgets. The finest Frontier cuisine is available at the Bukhara (Maurya Sheraton), Frontier (Ashoka Hotel) and Baluchi (The Hilton).\n" +
"\n" +
"At the other end of the scale, there are the many popular roadside eateries around Jama Masjid and Nizamuddin where kababs, rotis and biryani are the order of the day.\n" +
"\n" +
"Every five-star hotel in the city has a Chinese restaurant, while most markets in South Delhi have a medium-budget Chinese eateries. The popularity of this cuisine can be gauged by the innumerable Chinese food outlets of the \"meals-on-wheels\" and kiosk variety. The growing sophistication of the Delhite's palate is discernable in the increasing number of specialty restaurants - EI Arab (Regal Building), Dum Pukht in Awadh (Maurya Sheraton), Kashmiri food at Chor Bizarre (Hotel Broadway), Thai food at Baan Tahi (The Oberoi) and Sukothai ( Hauz Khas village), Japanese food at Tokyo (Ashoka Hotel) and Osaka (Haus Khas village), Tibetan food at eateries near Chanakya Theatre, and Mexican food at Rodeo (Connaught Place).\n" +
"\n" +
"South Indian food is another favorite, the vegetarian variety of which is best enjoyed at Sagar (Defence Ccolony), Sagar Ratna (Lodhi Hotel) and Dasaprakash (Hotel Ambassador). Coconut Grove (Ashok Yatri Niwas) offers excellent non-vegetarian cuisine from south India.\n" +
"\n" +
"The best of continental cuisine can be eaten at five-star hotels, the Orient Express (Taj Palace) and Captains Cabins (Taj Man Singh), though numerous multi-cuisine restaurants also offer continental food. Keeping pace with the changing face of the city are the growing number of fast food outlets, which serve all a large varity of cuisines\n" +
"\n" +
"A delightful spot offering a range of Indian Cuisine are the food stalls at Dilli Haat. Here, the cuisine of different states is made available at very moderate rates. Set in the midst of a spacious craft bazaar these cafes are a very pleasant place to enjoy food. For the more intrepid, eateries such as those at Pranthe Wali Gali, or chaat at Bengali Market and Sunder Nagar, bhelpuri at Greater Kailash and sweetmeats from Annapoorna and Ghantewala can be part of the gastronomical tour of Delhi.\n" +
"\n" +
"Delhi is also synonymous with the omnipresent tandoori chicken and tandoori roti, which, when freshly prepared from the tandoor, makes a delicious meal. This is often available at roadside dhabas at a moderate cost. ");
    }//GEN-LAST:event_cuisineActionPerformed

    private void restrauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restrauActionPerformed
        // TODO add your handling code here:
        infoeat.setText("Hotel Grand Tushar\n" +
"GT Road\n" +
"\n" +
"3 Star Hotel With All The Luxurious Facilities like Laundary Services, Travel Desk, Well Furnished Rooms etc\n" +
"Business can Provide\n" +
"Restaurant Alacarte, Restaurants & Bars, Hotel, Hall,\n" +
"\n" +
"    View Phone Numbers\n" +
"\n" +
"    Plot no 178, Bagh Bhatiyari Chaudhary More GT Road Ghaziabad\n" +
"\n" +
"Mughal Mahal Restaurant\n" +
"Rajendra Place\n" +
"\n" +
"Bar-Resturant, Free Home Delivery, Veg-Non Veg Resturant\n" +
"Business can Provide\n" +
"Restaurant Alacarte, Restaurant Bar, Restaurants & Bars, Mughal Mahal Restaurant,\n" +
"\n" +
"    View Phone Numbers\n" +
"\n" +
"    7 Sethi Bhawan Pusa Road Rajendra Place Delhi\n" +
"\n" +
"York Hotel\n" +
"Connaught Place\n" +
"\n" +
"The YORK HOTEL is even more inviting than before. With state of the art business facilities, the comfort of central air-conditioning and personalized service. We’ve always worked to make the YORK a home...\n" +
"Business can Provide\n" +
"Restaurant Alacarte, Restaurant Bar, Restaurants & Bars, York Hotel,\n" +
"\n" +
"    View Phone Numbers\n" +
"\n" +
"    K-10/11 Connaught Circus Connaught Place Delhi\n" +
"\n" +
"Swati Hotels\n" +
"Karol Bagh\n" +
"\n" +
"3 Star Hotel, Hotel Resort, 2 Star Hotel, Hotel 3 Star in Delhi\n" +
"Business can Provide\n" +
"Restaurant Alacarte, Restaurant Bar, Restaurants & Bars, Swati Hotels,\n" +
"\n" +
"    View Phone Numbers\n" +
"\n" +
"    17A/32 Gurudwara Road, W.E.A Karol Bagh Delhi\n" +
"\n" +
"Gulati Restaurant & Foods Pvt Ltd\n" +
"Pandara Road\n" +
"\n" +
"    Growing with us\n" +
"    5Years\n" +
"\n" +
"Undoubtedly, the most trusted and revered place for authentic Indian, Mughlai & Tandoori delicacies for over four decades. Set right in the heart of the national capital, this, 130+ cover restaurant,...\n" +
"Business can Provide\n" +
"Restaurant Alacarte, Restaurants & Bars, Gulati Restaurant & Foods Pvt Ltd, Gulati Restaurant & Foods Pvt Ltd, Pandara Road,\n" +
"\n" +
"    View Phone Numbers\n" +
"\n" +
"    6 Pandara Market Pandara Road New Delhi\n" +
"\n" +
"One Two One Food Corner\n" +
"Sector 57 Noida\n" +
"\n" +
"Lunch-Corporate, Dinner-Corporate, Parties-Corporate\n" +
"Business can Provide\n" +
"Restaurant Alacarte, Restaurants & Bars, One Two One Food Corner, Sector 57 Noida, One Two One Food Corner,\n" +
"\n" +
"    View Phone Numbers\n" +
"\n" +
"    B-70 Sector 57,Noida Sector 57 Noida Noida\n" +
"\n" +
"Anjlika Pastry Shop\n" +
"Rajouri Garden\n" +
"\n" +
"    Growing with us\n" +
"    8Years\n" +
"\n" +
"A Unit Of Anjlika Foods Birthday Cakes,pastries,cookies Breads,fast Food & Icecreams Speciality:almond Biscotti\n" +
"Business can Provide\n" +
"Restaurant Alacarte, Restaurants & Bars, Confectionery, Bakery & Confectionery,");
    }//GEN-LAST:event_restrauActionPerformed

    private void dhabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhabaActionPerformed
        // TODO add your handling code here:
        infoeat.setText("Obviously, I don’t need to brag about the importance of Dhabas (Roadside Eating Joints) stationed on almost all highways in India. Whether it is about feeding our gurgling stomachs or reflecting the authentic taste of any region or the hospitality with which the food is served, these roadside eateries certainly know the way to win one’s heart. It is amazing to see how some of these Dhabas, which were once merely stopovers for travelers, have become destinations unto themselves. It can be safely said that Dhabas are serious business. Ok, enough of talking! Let me also get back to my business and present to you a list of Dhabas that you must stop by if you are travelling on Indian highways:\n" +
"\n" +
"Mr Sanjay Dhaba, Srinagar-Leh Highway\n" +
"Mr-Sanjay-Dhaba\n" +
"Stop by this lone Dhaba situated 50kms from Leh on the Srinagar-Leh Highway. With nothing more than a roughly maintained concrete shack, this place is still a paradise for travellers. You will see many foreign travellers basking and having black tea here. However, as an Indian you will love to savour the freshly prepared aaloo parantha and gobhi ki sabzi along with a refreshing cup of tea.\n" +
"\n" +
"Giani Da Dhaba, Kalka-Shimla Road, NH 22\n" +
"Giani-D-Dhaba\n" +
"More of a restaurant and less of a Dhaba…call it by any name; Giani is certainly a great food haunt in Dharampur, situated on Shimla- Kalka Road NH 22. A well maintain eatery with nice ambiance and great food, Giani is nothing short of treat on the way to awe-inspiring Shimla!\n" +
"\n" +
"Sukhdev Dhaba, G.T Road, Murthal NH 1\n" +
"Sukhdev-Dhaba-Haryana\n" +
"You just cannot ignore this classy place situated on GT Road, Murthal NH 1. Once a small shack catering to the appetite of truck drivers who ply on these roads, Sukhdev Dhaba or the Amrik Sukhdev Dhaba is now a serious affair. A tall, well-maintained AC building is what stands instead of the thatched-hay shack, serving sumptuous Indian as well as Chinese cuisine to the starving travellers who make sure to stop nowhere else but here. Amritsari Kulcha and aaloo paratha with tongue slurping white butter is the delight of Sukhdev… The taste and the feel are just unforgettable!\n" +
"\n" +
"Karnal Haveli, G.T Road, Karnal, NH 1\n" +
"Karnal-Haveli\n" +
"No, I am not disoriented on my topic of this blog but when it comes to highway and food, you ought to include Karnal Haveli in the list. I would call it a ‘Dhaba Redefined’, Karnal Haveli has every reason to make it to the list of popular highway Dhabas that you must stop by. Situated on the GT Road, Karnal NH 1, this place serves authentic Punjabi cuisine. The rustic influence on the exterior and interior décor of the restaurant adds to the fame of the place and an amusement park for kids is yet another asset here.\n" +
"\n" +
"Grand Lassi Shop, Zirakpur-Patiala Road, NH 21\n" +
"Grand-Lassi-Shop\n" +
"You are going to love this place! Situated on the Zirakpur – Patiala Road, NH 21, Grand Lassi Shop offers some lipsmacking Lassi and heavenly Aaloo Parantha topped with semi-melting butter, chana (Chick peas) and homemade yogurt. This place is 25kms away from Chandigarh and is quiet easy to find!\n" +
"\n" +
"Puran Singh Da Dhaba, Near Ambala City, NH 1\n" +
"puransingh-da-dhaba\n" +
"Get ready for some Punjabi Treat at Puran Singh Da Dhaba. Located on NH 1, somewhere near Ambala City, this place is an absolute delight. Don’t think about the ambiance once you are here or else you will miss out on a great place to eat in Punjab! Try Keema Kaleji, Kabab, Chicken Curry and Mutton curry with ‘Kadak’ Tandoori Roti or you can even try the sumptuous Kadhi Chawal that attracts many vegetarians here.\n" +
"\n" +
"Cheetal Grand, Delhi-Dehradun Highway, Near Khatauli\n" +
"Cheetal-Grand-Khatauli\n" +
"It may be a restaurant, but Cheetal Grand on the Delhi-Dehradun Highway is one place that you must visit if you are on the highway. From the traditional dal, sabzi, roti, chawal to grilled sandwiches and cold coffee with ice cream, you name it and you get it! A neat restaurant with nice ambiance and surroundings, Cheetal, situated at as short distance from Khatauli, Muzzafarnagar can be a great food haunt. Try the tubular omellette and also the paneer pakodas here.\n" +
"\n" +
"Bhajan Tadka Dhaba, Gajraula, NH 24\n" +
"bhajan=dhaba-gajraula\n" +
"This is one of the most picturesque Dhaba that I have seen. Neat and clean area with a thatched-hay shacks and delectable food, if you are by any chance travelling on NH 24 and you are anywhere near Gajraula, then you have to visit this place. This highway Dhaba offers great food at reasonable prices; try paneer butter masala, kadhi pakora along with garlic lachchha here and believe me you shall never forget the taste!\n" +
"\n" +
"Sharma Dhaba, Jaipur-Sikar Road\n" +
"sharma-dhaba\n" +
"Sharma Dhaba brings you Rajasthan on a platter! Situated on Jaipur-Sikar Road, Sharma Dhaba is one of its kinds. They serve authentic veg Rajasthani delicacy and their Mawa Naan is to die for! There are two dining areas that you can choose from, one is just off the road and other is in the backside and is known as Sharma Garden. Try Paneer Butter Masala, Malai Matar, Missi Roti and Dal Tadka here.\n" +
"\n" +
"Rao Dhaba, Delhi-Jaipur Highway, NH 8\n" +
"Rao-Dhaba\n" +
"You are about to get fed with some of the best Dhaba food ever! At Rao’s Dhaba, you are likely to lick your fingers after finishing your delectable meal. Situated on National Highway 8 on Delhi-Jaipur Road, this Dhaba is known for its yummilicious non-veg and veg Indian cuisine; one thing you must try here is paneer butter masala with tandoori naan.\n" +
"\n" +
"Ummiya Annapurna, Anand District Gujarat, NH 8\n" +
"Ummiya-Annapurna\n" +
"This eatery is near the bypass that connects the new expressway in Gujarat; well technically it is still on NH 8 in Anand district. However, you don’t need a reason to visit this incredible place! Serving you the right taste of Kathiyawad (precisely beckons SPICE AND CHILLI, unlike Gujrati cuisine). The food here is prepared over wood fire, thus expect rustic flavour in everything that you eat. You must try lassan aaloo, besan gatta and sev tamatar with rotla (local bread) here.\n" +
"\n" +
"Ramdev Dhaba, Mumbai-Pune Highway, Near Nigdi\n" +
"Ramdev-Dhaba\n" +
"Go vegan at Ramdev Dhaba and enjoy some of the most delectable Rajasthani food. Situated on the Mumbai- Pune Highway at Nigdi, this place is great to fill your stomach right! Must-try items here are Dal Baati and Rabdi.\n" +
"\n" +
"Sunny Da Dhaba, Old Mumbai-Pune Highway\n" +
"Sunny-Da-Dhaba\n" +
"If you are travelling from Pune to Lonavala through Old Mumbai-Pune Highway, then you ought to pay Sunny Da Dhaba a visit. The tin-shed Dhaba with long decorated tables and some out of the box food will leave you awestruck. You are going to love Rajoli Kabab, Tandoori Pomfret, Dal Bati and Jalebi here.\n" +
"\n" +
"Jai Hind Deluxe Dhaba, Kaneriwadi, NH 4\n" +
"Jai-Hind-Deluxe-Dhaba\n" +
"With a patriotic banner, Jai Hind Deluxe Dhaba is your savior if you are on National Highway 4, somewhere around Kaneriwadi. The Dhaba has good seating arrangements and it offers authentic taste of local food. You can halt here and relax while munching on some tasty food.\n" +
"\n" +
"Shree Sai Ashirwad Dhaba, Muskura, NH 7\n" +
"Shree-Sai-Ashirwad-Dhaba\n" +
"The rainbow DO inside the Dhaba is fantastic and the food is just the kind you need on a highway. Shree Sai Ashirwad Dhaba is situated on National Highway 7 near Muskura, Madhya Pradesh. The Dhaba offers delicious local food and a must try here would be Dal Bafla.\n" +
"\n" +
"Sher-e-Punjab Dhaba, Kolkata-Digha Road, NH 6\n" +
"Sher-e-Punjab-Kolaghat\n" +
"Sher-e-Punjab is situated on the National Highway between Kolkata and Digha and is known for hoisting the Punjabi flag high in West Bengal. It is one of those well-maintained highway restaurants-cum-Dhabas that serve some really lip smacking food. You would like to try the mixed platter and chicken tikka masala here.\n" +
"\n" +
"Azad Hind Dhaba, Kolkata, NH 1\n" +
"azad-hind-dhaba\n" +
"24hrs food service in Kolkata and yummilicious food is what keeps Azad Hind Dhaba a personal favourite of travellers. The Dhaba is situated on National Highway 1, Kolkata and offers authentic Punjabi cuisine. There are two sections, one AC and the other Non AC, so you can decide where you want to sit, although the service in both the sections is outstanding. Order Chicken Tikka Masala and Dal Makhani here.\n" +
"\n" +
"Samaroh En Dees Dhaba, Bhomoraguri to Sonitpur, 37A Highway Connector\n" +
"Samaroh-en-dees-tezpur\n" +
"You will certainly fall for this place – its extensive menu, location and design. Situated on the road to Tezpur (37A highway connector) between Bhomoraguri and Sonitpur, it is a great place to relish the taste of authentic Assamese cuisine. The Pigeon curry is the highlight of the place, although you can try Aaloo pitika in case you are a vegetarian.\n" +
"\n" +
"Chilika Dhaba,Barkul, NH 5\n" +
"chilka-dhaba\n" +
"You have every reason to like this place, delicious seafood, neat and clean ambiance and great surroundings.  Bask on the manji and savour the taste of Orissa; you may not want to miss out on Chilli Prawns and Giant Crabs here. Also, the Dhaba serves some great vegetarian items that you may like to munch upon. Situated on NH 5 in Barkul, this Dhaba is at a short distance from the famous Chilika Lake, so after filling your stomach you can head to capture the beauty of the same.");
    }//GEN-LAST:event_dhabaActionPerformed

    private void fastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastActionPerformed
        // TODO add your handling code here:
        infoeat.setText("Chandni Chowk, often called the food capital of India, is famous\n" +
"for its street food. The variety consists of snacks, especially chaat.\n" +
"If you wish to enjoy it, shed your high-brow attitude to soak in the flavours and delicacies. Come on, everybody... Yes, it's a kind of celebration in congregation. Chandni Chowk resembles a fair everyday. The streets are lined with halwais (sweet-sellers), namkeenwallahs (sellers of savouries) and paranthewallahs\n" +
"(sellers of rich, flaky breads soaked in ghee).\n" +
"\n" +
" \n" +
"\n" +
"A good idea would be to start with the Paranthewali Gali. It became a famous gourmet locality when the parantha shops moved here in the 1870s. This lane has been the haunt of many celebrities of India. In the years after Independence, Pandit Jawahar Lal Nehru and his family members - Indira Gandhi and Vijaylaxmi Pandit - came here to take their parantha meals. Jayaprakash Narayan and Atal Behari Vajpayee were also among the regular visitors.\n" +
"\n" +
" \n" +
"\n" +
"Though the number of shops in this lane has reduced - one wonders if their owners are more interested in McDonald's franchises - there still are a few left from the good old days. Perhaps the oldest among these is Pt Gaya Prasad Shiv Charan, established in 1872. Others include Pandit Devi Dayal's (1886) and Kanhaiya Lal Durga Prasad's Parantha Shop (1875). The paranthas are fried in pure ghee in cast-iron pans. They are served with Mint Chutney, Banana - Tamarind Chutney, vegetable pickle and Aloo Subzi. Half a century back, you could get only a few varieties - Aloo Parantha, Gobhi Parantha and Matar Parantha, stuffed with potato, cauliflower and peas respectively. While these continue to be the most popular, there are several new variants. These include lentils, fenugreek, radish, papad, carrot and mixed. Besides, there are paranthas which cost slightly more and include those stuffed with paneer, mint, lemon, chilly, dry fruits, cashew, raisins, almond, rabdi, khurchan, banana, karela, lady's finger and tomato.\n" +
"\n" +
" \n" +
"\n" +
"The real flavour of the Delhi street food lies in the chaat. The original chaat is a mixture of potato pieces, crispy fried bread, Dahi Bhalla, gram and tangy-salty spices. The mixture is garnished with sour home-made Indian chilly and saunth (dried ginger and tamarind sauce), fresh green coriander leaves and yoghurt. However, there are several other popular variants now, including the one with an Aloo Tikki. Let us explore a few of the chaat shops. Shree Balaji Chaat Bhandar (1462, Chandni Chowk; Noon to 10pm) is perhaps the best and most popular chaatwallah in Chandni Chowk. We particularly recommend the Papdi Chaat with its liberal inclusion of Kachaalu Chutney, Khasta Papdis and saunth. Bishan Swaroop (1421, Chandni Chowk; 10am to 10pm) is one of those gems tucked away in the chaotic by-lanes of Chandni Chowk which keep alive the magic of another time, another taste.\n" +
"\n" +
"Since 1923, this tiny little stall has dished out just three items: awesome Aloo Chaat, fabulous Aloo ke Kulle and mouth-watering Fruit Chaat.\n" +
"\n" +
" \n" +
"\n" +
"You cannot afford to give a miss to the authentic chaat at Lala Babu Chaat Bhandar (77, Chandni Chowk, Near McDonald's; 11am to 10pm). Glorious Gol Gappe served with a type of Jal Jeera that's packed with harad (a digestive), kachoris stuffed with potato and peas, Gobhi-Matar Samosas, Dahi Bhalla and Matar Paneer Tikki are the fastest-selling items here. Jugal Kishor Ramji Lal (23, Dujana House, Chawri Bazaar, Chandni Chowk; 10.30am to 10pm) is best known for the Fruit Chaat that has become a quintessential part of the sounds and sights of Chandni Chowk. Though they do offer a version of Pao Bhaji and Aloo Tikki, it's the Fruit Chaat that is the winner here. Dahi Bhalla need not always be a part of chaat; it can be served as a principal dish as you will find at Natraj Dahi Bhalla. The delicacy called Dahi Bhalla is a deep-fried urad dal dumpling smothered in whipped curd. Often, it is streaked with chocolatebrown laces of sweet-sour tamarind chutney. Pink pomegranate seeds glisten in the folds of the curd. Natraj is located near Bhai Mati Das Chowk at the turning to Chandni Chowk metro station.\n" +
"\n" +
" \n" +
"\n" +
"Kachori, usually stuffed with pulses and served with potato curry, is another delicacy that makes your mouth water. Jung Bahadur Kachori Wala (1104, Chhatta Madan Gopal, Chandni Chowk; 10.30am to 8pm) is perhaps the most famous for its Urad Dal Kachori, which is served with Aloo Subzi. This place is surely worth the adventure.\n" +
"\n" +
" \n" +
"\n" +
"On the sweeter side, Rabdi Faluda is a must. And the place to have it is Giani di Hatti near the Fatehpuri Mosque. It has now become an ice-cream parlour specializing in exotic flavours like Litchi and Bubblegum. Apart from standard ice creams, they also serve milkshakes, fruit shakes, ice-cream shakes and sundaes. If you are interested in kulfi - a flavoured frozen dessert made of milk - venture towards the Ajmeri Gate. The popular name here is Siya Ram Nannumal Kulfiwale (629, Gali Lodan, Ajmeri Gate; 7am to 4pm). What you get here is kulfi as kulfi should be - sinful, scrumptious and oh-so-splendid! Order any flavour - Kesar, Pista, Rose, Kewra, Banana, Mango, or Pomegranate. Or better still, order one of each.... Indulge!\n" +
"\n" +
" \n" +
"\n" +
"Coming back to Chandni Chowk, you meet the Old and Famous Jalebiwala just before you enter Dariba Kalan. Refresh yourself with a delicious plate of hot jalebis - a sweet made by deepfrying batter in a kind of pretzel shape and then soaked in syrup. Also, don't miss the Jama Masjid area that buzzes with activity. The aroma of food wafts to your nose from the Urdu Bazaar facing Gate No. 1 of the Masjid and a side street called Matia Mahal. The smell of fresh fish, aromatic kebabs and fried chicken is in the air. Vendors sell kebabs and tikkas (made of buffalo meat) wrapped in rumali roti (paper-thin bread) at throwaway prices. The Mutton Burrahs here are easily the best in the city. They are practically the only place to serve Nihari and Paaya, which are all sold out by 8.30am Other unmissables are Stew, Mutton Korma, Shammi Kabab and Shahjahani Korma.\n" +
"\n" +
" \n" +
"\n" +
"Ghantewala at Chandni Chowk is more than 200 years old. The sweets here are prepared in pure desi ghee. Highly recommended are the Sohan Halwa Papdi, Pista Samosa and Badam Burfi - truly sinful pieces of heaven on earth.\n" +
"\n" +
" \n" +
"\n" +
"Delhi's only tea boutique worth its name, this place bursts with atmosphere. Midway between New and Old Delhi, tourists in the know and locals in search of that magical cuppa beat a retreat to this store-cum-drawing room. Even if tea is not your thing, you can pick up gifts for friends. Even though it has distinctly frayed at the edges, the restaurant offers the cuisine it truly pioneered in the city - Dal Makhni, Butter Chicken, Reshmi Kabab, Murgh Musallam. After all these years, the Tandoori Chicken is still succulent. Chor Bizarre is one of the few restaurants to serve Kashmiri food and attempts to replicate a 'thieves market' in its decor. Specially recommended for non-vegetarians is the Tabak Maaz. Also good are the Yakhni, Rishta and Goshtaba, besides the wonderful greens - Haaq.");
    }//GEN-LAST:event_fastActionPerformed

    private void monumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monumentsActionPerformed
        // TODO add your handling code here:
        infoent.setText("Humayun's Tomb -\n" +
"built by the wife of Humayun, Haji Begum in the mid 16th century, this red sand stone structure is considered to be the predecessor of Taj Mahal. The structure is one of the best example of Mughal Architecture. Humayun's wife is also buried in the red and white sandstone, black and yellow marble tomb. The entry in the complex is free on Fridays.\n" +
"\n" +
"Old Fort -\n" +
"It is believed that the Pandavas had built their capital, Indraprastha at the place where the old fort stands today. This fort, now in ruins, was the seat for administration for many emperors. The legendary Prithviraj Chauhan ruled from here till he was defeated by Abdali in the battle of Panipat. A new light & sound show is held by the Department of Delhi Tourism every evening. Timings and Tickets are available from the tourist office.\n" +
"\n" +
"Safdarjung Tomb\n" +
"The Safdarjang tomb is besides the of Safdarjang airport. This tomb was built by the Nawab of Avadh for his father. The structure is one of the finest example of architecture of its time and tells a saga of the last remnants of a dying empire..\n" +
"\n" +
"Jantar Mantar\n" +
"Few minutes walk from Connaught Place is is a strange collection of solomon coloured structures. These were built by Maharaja Jai Singh and is actually an observatory. Though not as large as its compatriot in Jaipur Jantar Mantar at Delhi also an attraction for the tourists. The astonishing part of these observatories is that they can calculate many astronomical movements very accurately.\n" +
"\n" +
"Red fort -\n" +
"Built in Red Sand stone this imposing fort is 3 kms in perimeter with the height of the wall varying from 18 to 30 meters at places. When the Red fort was being built Yamuna used to flow on its one sides and there were deep moats on the other. Today Yamuna flows almost a kilometer away from the fort and the moats have dried up. In the evening the Delhi Tourism organises a light and sound show which narrates the history of Delhi in context of the Red Fort.\n" +
"\n" +
"The Lahore gate, the main entrance, has some emotions and sentiments attached with the Indian independence as the Tricolour flutters on the top of this gate. On 15th August the Indian Prime minister addresses the nation from here. As soon one enters in the fort from the Lahore gate There is a small Bazaar, here all kinds of items are available. This Shopping arcade was known as the Mina Bazaar and was open only to women on Thursdays's during the Mughal era.\n" +
"\n" +
"The arcade leads to the Naubat Khana or the drum house where the Musicians used to play drums on the arrival of Emperors or princes. Just above the Naubat Khana is the Indian war memorial museum which has a rich collection of armours, guns, swords, and other items related to war.\n" +
"\n" +
"The Dewan-i-Am or the place of public hearing had a wall paneled with marble in laid with precious stone which were removed during the mutiny of 1857. The Dewan-i-Khas or the place for special hearing was the area where the emperor used to hold meetings with his ministers. Next to Dewan-i-Khas are the royal baths or the Hammams and Shahi Burj which are closed for public viewing. The white marbled Moti Masjid or the pearl mosque was the private mosque for Aurangzeb.\n" +
"\n" +
"Qutab Minar\n" +
"In 1199, Qutbuddin raised the Qutab Minar either as a victory tower or as a minaret to the adjacent mosque. From a base of 14.32 mtrs. it tapers to 2.75 mtrs. at a height of 72.5 mtrs. It is still the highest stone tower in India, one of the finest stone tower in India, one of the finest Islamic structures ever raised and Delhi's recognised landmark. It was completed by the Sultan's successor and son-in-law, Iltutmish. The tomb of Iltutmish, which he himself built in 1235, is nearby, Its interiors are profusely decorated with calligraphy, though the dome has collapsed. ");
    }//GEN-LAST:event_monumentsActionPerformed

    private void museumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_museumActionPerformed
        // TODO add your handling code here:
        infoent.setText("New Delhi is home to several historic sites and museums. The National Museum which began with an exhibition of Indian art and artefacts at the Royal Academy in London in the winter of 1947–48[71] was later at the end was shown at the Rashtrapati Bhawan in 1949. Later it was to form a permanent National Museum. On 15 August 1949, the National Museum was formally inaugurated and currently has 200,000 works of art, both of Indian and foreign origin, covering over 5,000 years.[72]\n" +
"\n" +
"The India Gate built in 1931 was inspired by the Arc de Triomphe in Paris.[69] It is the national monument of India commemorating the 90,000 soldiers of the Indian Army who lost their lives while fighting for the British Raj in World War I and the Third Anglo-Afghan War.[69]\n" +
"\n" +
"The Rajpath which was built similar to the Champs-Élysées in Paris is the ceremonial boulevard for the Republic of India located in New Delhi. The annual Republic Day parade takes place here on 26 January.\n" +
"The Rajghat, the final resting place of Mahatma Gandhi.\n" +
"\n" +
"Gandhi Smriti in New Delhi is the location where Mahatma Gandhi spent the last 144 days of his life and was assassinated on 30 January 1948. Rajghat is the place where Mahatma Gandhi was cremated on 31 January 1948 after his assassination and his ashes were buried and make it a final resting place beside the sanctity of the Yamuna River. The Raj Ghat in the shape of large square platform with black marble was designed by architect Vanu Bhuta.\n" +
"\n" +
"Jantar Mantar located in Connaught Place was built by Maharaja Jai Singh II of Jaipur. It consists of 13 architectural astronomy instruments. The primary purpose of the observatory was to compile astronomical tables, and to predict the times and movements of the sun, moon and planets.\n" +
"\n" +
"New Delhi is home to Indira Gandhi Memorial Museum, National Gallery of Modern Art, National Museum of Natural History, National Rail Museum, National Handicrafts and Handlooms Museum, National Philatelic Museum, Nehru Planetarium, Shankar's International Dolls Museum.[73] and Supreme Court of India Museum.[74]\n" +
"\n" +
"In the coming years, a new National War Memorial and Museum will be constructed in New Delhi[75][76] for ₹4000 million (US$60 million).[77][78]\n" +
"\n" +
"New Delhi is particularly renowned for its beautifully landscaped gardens that can look quite stunning in spring. The largest of these include Buddha Jayanti Park and the historic Lodi Gardens. In addition, there are the gardens in the Presidential Estate, the gardens along the Rajpath and India Gate, the gardens along Shanti Path, the Rose Garden, Nehru Park and the Railway Garden in Chanakya Puri. Also of note is the garden adjacent to the Jangpura Metro Station near the Defence Colony Flyover, as are the roundabout and neighborhood gardens throughout the city.");
    }//GEN-LAST:event_museumActionPerformed

    private void theaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theaterActionPerformed
        // TODO add your handling code here:
        infoent.setText("    Abhimanch\n" +
"    National School of Drama,\n" +
"    Bhawalpur House,\n" +
"    Ph: 23389402, 23389769, 23389138\n" +
"\n" +
"    Aifacs Auditorium\n" +
"    Rafi Marg, Ph: 23711315\n" +
"\n" +
"    Agha Khan Hall\n" +
"    6, Bhagwandas Road, Ph: 23381163\n" +
"\n" +
"    Air Force Auditorium\n" +
"    Subroto Park,\n" +
"    Ph: 25692386,25693732, 25692834\n" +
"\n" +
"    Akshara Theatre\n" +
"    11-12B, Baba Kharak Singh Marg,\n" +
"    Ph: 23361075, 23732083, 23742083\n" +
"\n" +
"    Ambedkar Auditorium\n" +
"    1, Ashok Road, New Delhi.\n" +
"    Ph: 23389182\n" +
"\n" +
"    American Centre\n" +
"    24, Kasturba Gandhi Marg,\n" +
"    Ph: 23316841, 23314251\n" +
"\n" +
"    Banarasidas Chandiwala Smarak Trust Society\n" +
"    Chandiwala Estate, Maa Anandmai\n" +
"    Marg, Kalkaji. New Delhi.\n" +
"    Ph: 26826208-10\n" +
"\n" +
"    British Council Division\n" +
"    17, Kasturba Gandhi Marg,\n" +
"    Ph: 23711401, 51494226\n" +
"\n" +
"    FICCI Auditorium\n" +
"    Tansen Marg,\n" +
"    Ph: 23738760-70, 23357369\n" +
"\n" +
"    French Cultural Centre\n" +
"    2, Aurangzeb Road, Ph: 23014682\n" +
"\n" +
"    Ghalib Auditorium\n" +
"    Mata Sundari Lane,\n" +
"    Ph: 23236518, 23232583\n" +
"\n" +
"    Hungarian Cultural Centre\n" +
"    1-A, Janpath, Ph: 23014497\n" +
"\n" +
"    ICCR Auditorium\n" +
"    Azad Bhavan, Indraprashtha Estate,\n" +
"    ITO, New Delhi.\n" +
"    Ph: 23379309, 23370698\n" +
"\n" +
"    India Habitat Centre\n" +
"    Lodi Road, Ph: 24682222\n" +
"\n" +
"    India International Centre\n" +
"    40, Maxmullar Marg, Lodhi Road.\n" +
"    Ph: 241619431\n" +
"\n" +
"    ISRAEL Cultural Centre\n" +
"    3, Aurangzeb Road, New Delhi.\n" +
"    Ph: 30414500\n" +
"\n" +
"    Italian Cultural Centre\n" +
"    50-E, Chandragupta Marg,\n" +
"    Chanakyapuri, Ph: 26871901\n" +
"\n" +
"    Kamani Auditorium\n" +
"    1, Copernicus Marg, Ph: 23388084\n" +
"\n" +
"    Lok Kala Manch\n" +
"    20, Institutional Area, Lodi Road,\n" +
"    New Delhi.\n" +
"    Ph: 24644421, 24602366\n" +
"\n" +
"    LTG Auditorium\n" +
"    Copernicus Marg,\n" +
"    Ph: 23389713, 23384111\n" +
"\n" +
"    Max Mueller Bhavan\n" +
"    3, Kasturba Gandhi Marg,\n" +
"    Ph: 23329506,4,5,2\n" +
"\n" +
"    Mavalankar Auditorium\n" +
"    Rafi Marg, Ph: 23719780\n" +
"\n" +
"    National School Of Drama\n" +
"    Bhagwan Das Marg, Ph: 23389769\n" +
"\n" +
"    Pyare Lal Bhawan\n" +
"    (Gandhi Memorial Hall),\n" +
"    2, Bahadur Shah Zafar Marg\n" +
"\n" +
"    Rabindra Bhavan\n" +
"    Lalit Kala, Sangeet Natak, Sahitya\n" +
"    Akademi, 35, Feroze Shah Road,\n" +
"    Ph: 23386626\n" +
"\n" +
"    Rail Auditorium\n" +
"    National Rail Museum, Chanakyapuri.\n" +
"    Ph: 26881816, 26880939\n" +
"\n" +
"    Ramana Kendra\n" +
"    8, Institutional Area, Lodi Road.\n" +
"    Ph: 24626997\n" +
"\n" +
"    Sapru House\n" +
"    Barakhamba Road,\n" +
"    Ph: 23317248, 23310636\n" +
"\n" +
"    Sarai\n" +
"    The New Media Initiative Centre for\n" +
"    the Study of Developing Societies,\n" +
"    29, Rajpur Road,\n" +
"    Ph: 23960040, 23942199, 23983352\n" +
"\n" +
"    Siri Fort\n" +
"    Asiad Village Complex, Khelgaon\n" +
"    Marg,Ph: 26493370\n" +
"\n" +
"    Shri Ram Bhartiya Kala Kendra\n" +
"    Copernicus Marg, Ph: 23386428\n" +
"\n" +
"    Shri Ram Centre\n" +
"    Mandi House, Safdar Hashmi Marg,\n" +
"    New Delhi. Ph: 23714307\n" +
"\n" +
"    Studio Theatre\n" +
"    National School of Drama,\n" +
"    Bhawalpur House,\n" +
"    Ph: 23389402, 23389769, 23389138\n" +
"\n" +
"    Tagore Hall\n" +
"    Azad Bhawan, Indraprastha Estate,\n" +
"    Ph: 23319309, 23379309, 23379310\n" +
"\n" +
"    Teen Murti Auditorium\n" +
"    Teen Murti Bhawan,\n" +
"    Ph: 23015026, 23015333\n" +
"\n" +
"    TradeFair Authority of India\n" +
"    Pragati Maidan,\n" +
"    Ph: 23371582, 23371491\n" +
"\n" +
"    Triveni Conference Hall\n" +
"    Triveni Kala Sangam, 205,\n" +
"    Tansen Marg,\n" +
"    Ph: 23718833\n" +
"\n" +
"    Vigyan Bhavan\n" +
"    Maulana Azad Road,\n" +
"    Ph: 23022231, 23022182");
    }//GEN-LAST:event_theaterActionPerformed

    private void galleryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleryActionPerformed
        // TODO add your handling code here:
        infoent.setText("Delhi's artistic infrastructure was developed post 1947 by the efforts of the Delhi Shilpi Chakra (an artist group) and India's first private art gallery, the Dhoomimal Gallery. With the government's first five year plan (1951-56), India adopted a cultural policy that established the Lalit Kala Academy and the National Gallery of Modern Art in Delhi. This made Delhi an important centre for art, a status that had been earlier granted Bengal and Bombay. Contemporary Indian art is flourishing and Delhi has an ever changing roster of paintings and exhibitions in its galleries. Everything from abstract art to sombre studies of urban life can be found in these exhibits.\n" +
"\n" +
"National Art Gallery of Modern Art\n" +
"Jaipur House, India Gate, New Delhi-110001\n" +
"Phone.: 23382835\n" +
"Timings: 10.00 am to 5.00 p.m\n" +
"Closed: Monday\n" +
"One of India's major art galleries, the National Gallery of Modern Art was once the residence of the Maharaja of the Jaipur. Situated near India Gate at the Eastern end of Rajpath, it houses an excellent collection of works by both Indian and colonial artists dating from 1850. The gallery has a collection of more than 15,000 paintings, sculptures and graphics.\n" +
"\n" +
"Lalit Kala Akademi\n" +
"Rabindra Bhawan, Feroze Shah Road, New Delhi-110001.\n" +
"Phone.: 23387241-43\n" +
"Timing: 10.00 am to 6.00 pm (closed on Saturday and Sunday)\n" +
"This spacious gallery is spread over three floors and had its first national exhibition of art in 1958. The gallery holds the prestigious Triennale India in which 30 to 40 countries participate, and a national exhibition of photography and art is held. One always finds something interesting happening here, especially during the winter months.\n" +
"\n" +
"Triveni kala Sangam\n" +
"Tansen Marg, New Delhi.\n" +
"Phone.: 23718833\n" +
"Timing: 9.30 am to 5.30 pm (Closed on Sunday)\n" +
"A four galleried cultural complex including the basement gallery run by Art Heritage. Shridharni Gallery is the largest gallery here. Triveni Gallery has smaller format works on display. The complex has a sculpture court for exhibitions and a bookshop with unconventional books, journals and cassettes.\n" +
"\n" +
"\n" +
"Art Heritage\n" +
"205, Triveni Kala Sangam, Tansen Marg, New Delhi.\n" +
"Phone.:23718833.\n" +
"Timing: 11.00 am to 7.00 pm\n" +
"A respected name in the art world was founded in 1977 by Roshen Alkazi. The gallery holds regular exhibitions throughout the year of some of the best known artists in India.\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"Art Today\n" +
"A-1 Hamilton House, Connaught Place, New Delhi-110001.\n" +
"Phone.: 23320689 23352233\n" +
"Timing: 11.00 am to 7.00 pm\n" +
"It hosts the collections of the best artists and its exhibitions are often commercially high profile. The gallery produces well designed catalogues and posters.\n" +
"\n" +
" \n" +
"\n" +
"Dhoomimal Art Gallery\n" +
"8-A, Connaught Place, New Delhi-110001.\n" +
"Phone.: 41516056, 23359526\n" +
"Timing: 10.00 am to 7.00 pm\n" +
"It is One of the oldest commercial galleries which runs regular shows. Over the year, an entire spectrum of artists had their works displayed here.\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"Gallerie Ganesha\n" +
"Phone.: 9810005733, 29226043, 29217306.\n" +
"Timing: 10 am to 7 pm\n" +
"It is a gallery which primarily focuses on promoting talent in youth. Its huge collection includes paintings, graphics and sculptures.\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"Gallery Espace\n" +
"16, Community Centre, New Friends Colony, New Delhi.\n" +
"Phone.: 26326267\n" +
"Timing: 11.00 am to 6.00 pm\n" +
"The Gallery has carved a niche for itself because of its specialised, unconventional focus. The gallery also produces informative catalogues.\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"Garhi Lalit Kala Artist Studio\n" +
"Kala Kutir, East of Kailash, New Delhi.\n" +
"Phone.: 26432225\n" +
"Timing: 10.00 am to 6.00 pm\n" +
"It is a Place worth visiting place if you are interested in the live processes of art. This studio is a part of and is run, The Lalit Kala Academy. Well known artists from India and abroad often hold workshops and illustrated lectures here.\n" +
"\n" +
"LTG Gallery\n" +
"Copernicus Marg, New Delhi-110001\n" +
"Phone.: 23389713\n" +
"Timing: 11.00 am to 7.00 pm\n" +
"The gallery often displays meaningful exhibitions. Its group shows by ceramic artists, theme shows on Nelson Mandela, Mahatma Gandhi and Kashmiri immigrants have made an impact.\n" +
"\n" +
"\n" +
"\n" +
"The Village Gallery\n" +
"14, Hauz Khas Village, New Delhi.\n" +
"Phone.: 26853860\n" +
"Timing: 10.30 am to 6.30 pm\n" +
"This gallery has done innovative shows in graphic design, drawings and sketches by Satyajit Ray, Mono-rints by women inmates of Tihar Jail and Haku Shah's homage to Gandhiji with straw, rags and cotton wool.");
    }//GEN-LAST:event_galleryActionPerformed

    private void worshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worshipActionPerformed
        // TODO add your handling code here:
        infoent.setText("Jama Masjid -\n" +
"One of the Architectural gift given by Shah Jahan, Jama Masjid is one of the largest mosques not only in Delhi but in India. Completed in 1658 this Mosque has three gateways, Four angle towers and two 40 m high minarets. You can enter the mosque but take precaution to take off your shoes and make sure that you are properly dressed before entering. One can also go to the top of minarets. From here you can have a birds eye view of Delhi.\n" +
"\n" +
"The Bahai Temple\n" +
"Completed in 1986, the Bahai temple is set amidst pools and gardens, and adherents of any faith are free to visit the temple and pray or meditate silently according to their own religion. The structure is in lotus shape so it often called the lotus temple. The view of the temple is very spectacular just before dusk when the temple is flood lit.\n" +
"\n" +
"Nizam-Ud-Din Shrine\n" +
"The tomb of the famous sufi saint Nizam-ud-din Auliya is built on the way from Humayun's tomb. Inside the premises of the shrine is a tank which is surrounded by many other tombs. It is said that there was a controversy between the rulers of Tughlakabad and the saint over building this tank. The saint had said that the city of Tughlakabad will never flourish and so did it happen. The shrine also has the tomb of Amir Khusru and the grave of Jahanara, the daughter of Shah Jahan. It is worth visiting the shrine at around sunset on Thursdays, as it is a popular time for worship, and qawwali singers start performing after the evening prayers.\n" +
"\n" +
"Lakshmi Narayan Temple -\n" +
"This temple was build by G. D. Birla in 1938. This beautiful temple is located in the west of Connaught Place. The temple is dedicated to the goddess of prosperity and good fortune. The temple has well grafted gardens. It is also known as the Birla Mandir.\n" +
"\n" +
"ISKCON Temple -\n" +
"Completed in 1998, this is a complex of temples. Built on a hilly place this temple is dedicated to the Lord Krishna and was built by the Hare-Rama Hare- Krishna cult followers. This complex is elegantly build and is one of the largest temple complexes in India. Currently the main attraction of the temple are the Robort who enact and preach the Gita.\n" +
"\n" +
"Chattarpur Mandir -\n" +
"A complex of temples called Chattarpur mandir is located beyond the Qutab Minar in Mehrauli. Dedicated to Goddess Durga. Build in South Indian style the temple complex is spread over a large area with beautiful lawns and gardens. Though devotees visit these temples through the year, during the navratras devotees come from near and far. During the festivals there are special bus services to these temples.\n" +
"\n" +
"Bangla Sahib Gurudwara -\n" +
"A magnificent and spacious bungalow in Delhi owned by Raja Jai Singh Amber (Jaipur) who commanded great respect and honour in the court of Mughal Emperor Aurangzeb now enjoys the status of a holy shrine called Gurdwara Bangla Sahib. The eighth Guru Sri Harkishan had stayed here for a few months as guest of Raja Jai Singh. Since then it has become a place of pilgrimage for both, Hindus and Sikhs. They pay their respect to the memory of Guru Harkrishan, nominated as successor by the seventh Guru, Sri Har Rai. He passed away on October 6, 1661 A.D. When only a little over five year old, he had been tried and tested as a perfect fearless and fully illuminated soul.\n" +
"\n" +
"Sisgunj Gurudwara -\n" +
"Chandini Chowk the beautiful golden domes of the Gurudwara Sisgunj immediately strike your eye. It commemorates the site of the ninth guru of the Sikhs, Guru Teg Bahadur's martyrdom. The Guru was beheaded by Aurangzeb 1675. The gurudwara has been extended from time to time and it tough to tell apart the original structure anymore. ");
    }//GEN-LAST:event_worshipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Greeter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Greeter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Greeter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Greeter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Greeter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton air;
    private javax.swing.JButton cuisine;
    private javax.swing.JButton dhaba;
    private javax.swing.JButton exit;
    private javax.swing.JButton fast;
    private javax.swing.JButton gallery;
    private javax.swing.JButton hotels;
    private javax.swing.JTextArea infoacco;
    private javax.swing.JTextArea infoeat;
    private javax.swing.JTextArea infoent;
    private javax.swing.JTextArea infotrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton luxuryhotels;
    private javax.swing.JButton metro;
    private javax.swing.JButton monuments;
    private javax.swing.JButton motels;
    private javax.swing.JButton museum;
    private javax.swing.JButton rail;
    private javax.swing.JButton restrau;
    private javax.swing.JButton road;
    private javax.swing.JButton theater;
    private javax.swing.JButton worship;
    // End of variables declaration//GEN-END:variables
}
